CREATE TABLE data_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(200) NOT NULL,
    content    TEXT         NOT NULL,
    owner_id   BIGINT       REFERENCES users(id),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);